### PR TITLE
Update attributions

### PR DESCRIPTION
**Pull request by imnotbob**
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by tonesto7** [comment]
@ahndee:  Thank you for all of your work :)

**Comment by ahndee** [comment]
You're welcome. Glad to be able to contribute a little bit to this awesome code!

**Comment by tonesto7** [comment]
@ahndee Did you see the PM I sent you on ST forums?

**Comment by ahndee** [comment]
Yes - replied there. Was out with the family…

**Pull request merged**
