### PR TITLE
Update nest-thermostat.groovy

### PR DESCRIPTION
**Pull request by imnotbob**
Add C mode .5 degree changes
Fix to match standard thermostat capabilities as described by SmartThings (thermostatSetpoint, attributestates)
Fix Temp up down to work on older and newer ST app versions (multi-tile rboy)
Do not attempt temp changes in away mode
## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Description of Changes

C mode temp changes of .5 degrees.
## How Has This Been Tested?

Testing on my nests

### CODE REVIEW

**Comment by tonesto7** [comment]
Thanks for your work Eric...
These PR's are too large.

I just needed the Celsius changes. 

I don't want make changes to the overall device to make it like  R boy's...  I've not heard any complaints about the control

**Comment by imnotbob** [comment]
The rboy changes I think are the minimum set.

I expect there would have been more changes given the level of duplicate code.

I have tested these in my environment.

Eric

On Mar 19, 2016, at 11:22 PM, Tonesto7 <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for your work Eric...
These PR's are too large.

I just needed the Celsius changes.

I don't want make changes to the overall device to make it like R boy's... I've not heard any complaints about the control

**Comment by imnotbob** [comment]
Please give it a try.  You will see there are several places that temp changes are made and tested, and my view is this was the minimum number.   I have tested all this and it works in all my tests.

**Comment by tonesto7** [comment]
I will try it but I do not want to add that much stuff to the handler.  There are over 92 installs of the devices and almost no major issues.  By adding that code we are copying Rboy's and I don't think its necessary to change.  This is not me be a control freak I just think that this project stands out because it's not copying everyone else's code.

Going forward please split up the updates into new branch PR's.  I can't test your celsius changes without adding in the other code.

**Comment by desertblade** [comment]
I agree with tonesto7 on the rboy changes.  We have not had any complaints about up/down not working. I also have been trying to do smaller PRs, using branches.  

Naming convention question: I choose targetTempEvent because it mapped to Nest response of "target".  Should we stick with aligning to Nest?

Reviewing the Celsius changes they look good. Did not realize how much we set toInterger.

**Pull request closed without merging**
